server:
  port: 7001

logging:
  level:
    root: info
    com.casco: debug

spring:
  application:
    name: casco_operation_portal
  datasource:
    name: casco
#    url: jdbc:mysql://${MYSQL_HOST:172.30.81.114}:${MYSQL_PORT:3306}/casco_zhgs?useUnicode=true&characterEncoding=UTF8
#    username: root
#    password: 123456
    url: jdbc:mysql://${MYSQL_HOST:192.168.0.103}:${MYSQL_PORT:3306}/casco_zhgs?useUnicode=true&characterEncoding=UTF8
    username: root
    password: Casco123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  #  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


hive:
  datasource:
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: org.apache.hive.jdbc.HiveDriver
      #配置基本属性
#      url: jdbc:hive2://172.30.81.114:10011/test
#      username: root
#      password:
      url: jdbc:hive2://192.168.0.101:10000/mpom
      username: admin
      password: admin
      #配置初始化大小/最小/最大
      initialSize: 10
      minIdle: 10
      maxActive: 30
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 10


tomcatComponent:
  componentId: 10000
  tomcatStartPath: /opt/tomcat/bin/start.sh
  tomcatStopPath: /opt/tomcat/bin/stop.sh

#是否开启组件运行状态检测 0：不开启  1:开启（考虑到各开发所使用的的系统和服务器系统指令不一样，开发本地运行时建议关闭此功能）
checkComponentStatus: 1