server:
  port: 7521

spring:

  analysis:
    waitTime: 60000
    duration: 30

  mysql:
    name: combine
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.103}:${MYSQL_PORT:3306}/casco_zhgs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&nullCatalogMeansCurrent=true
    username: root
    password: Casco@123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  activiti:
    db-history-used: true
    async-executor-enabled: true
    async-executor-activate: true

  influx:
    url: http://192.168.1.103:8086
    user: root
    password: 123456

  kafka:
    bootstrap-servers: 192.168.1.101:9092,192.168.1.101:9092

    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      max-poll-records: 100
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000

kafka:
  topic:
    group-id: casco_opgw_combine_alarm
    topic-name: casco_opgw_signal_alarm